/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object ValuesApi {

  /**
   * 
   * 
   * Expected answers:
   *   code 204 :  (No Content)
   * 
   * @param id id of the item to be deleted
   */
  def valuesDelete(id: Int): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.DELETE, "http://localhost/swaggerDemo", "/api/Values/{id}", "application/json")
      .withPathParam("id", id)
      .withSuccessResponse[Unit](204)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 : Seq[String] (OK)
   */
  def valuesGet(): ApiRequest[Seq[String]] =
    ApiRequest[Seq[String]](ApiMethods.GET, "http://localhost/swaggerDemo", "/api/Values", "application/json")
      .withSuccessResponse[Seq[String]](200)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 : String (OK)
   * 
   * @param id The id of the item to be retrieved
   */
  def valuesGet_0(id: Int): ApiRequest[String] =
    ApiRequest[String](ApiMethods.GET, "http://localhost/swaggerDemo", "/api/Values/{id}", "application/json")
      .withPathParam("id", id)
      .withSuccessResponse[String](200)
        /**
   * 
   * 
   * Expected answers:
   *   code 204 :  (No Content)
   * 
   * @param value New value to be inserted
   */
  def valuesPost(value: String): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "http://localhost/swaggerDemo", "/api/Values", "application/json")
      .withBody(value)
      .withSuccessResponse[Unit](204)
        /**
   * 
   * 
   * Expected answers:
   *   code 204 :  (No Content)
   * 
   * @param id The id of the value to be changed
   * @param value The new value
   */
  def valuesPut(id: Int, value: String): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.PUT, "http://localhost/swaggerDemo", "/api/Values/{id}", "application/json")
      .withBody(value)
      .withPathParam("id", id)
      .withSuccessResponse[Unit](204)
      

}

